version: '3.9'

services:
  database:
    image: 'postgres:15'
    container_name: projeto-clinica
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - projeto_clinica:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s
    mem_limit: 500m


volumes:
  projeto_clinica:
    driver: local
